session_analytics:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: SFEDU02-KSB65579
      user: LYNX
      password: AkhilNikhil@123
      role: TRAINING_ROLE
      database: USER_DB_LYNX
      warehouse: LYNX_QUERY_WH
      schema: RAW
      threads: 4
      client_session_keep_alive: False