# Schema definitions for models
# Includes test configurations for key fields
# Author: Akhil Lokesh

version: 2

models:
  - name: session_summary
    description: "Session summary analytics table"
    columns:
      - name: sessionId
        tests:
          - unique
          - not_null 